[build]
  publish = "."
  command = "echo 'No build needed for static CRATE PEACH studio'"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate, public"

[[redirects]]
  from = "/grabber/*"
  to = "/grabber/:splat"
  status = 200