import test from 'node:test';
import assert from 'node:assert/strict';
import {defaults,presets,normalizeRecipe,generatePrompt,parseExport,SCHEMA} from '../studio/recipe.mjs';
test('Polish ignores retained groove settings and keeps vocal phrasing',()=>{const p=generatePrompt({...defaults,mode:'polish',humanize:12,quantize:50});assert.match(p,/Original timing and arrangement stay intact/);assert.doesNotMatch(p,/Grid correction|layback .* ms/);assert.match(p,/Preserve vocal timing/);});
test('One groove map with measurable bounds and protected anchor',()=>{const p=generatePrompt(defaults);assert.match(p,/54%/);assert.match(p,/layback 4 ms/);assert.match(p,/±8 ms/);assert.match(p,/Never apply blanket micro-warping/);assert.match(p,/one coherent timing map/);});
test('Nonfinite and out-of-bounds imports cannot escape limits',()=>{const r=normalizeRecipe({...defaults,peak:20,bass:-50,humanize:Infinity,mode:'invented',duration:900});assert.equal(r.peak,-.1);assert.equal(r.bass,-3);assert.equal(r.humanize,8);assert.equal(r.mode,'pocket');assert.equal(r.duration,72);});
test('Signed EQ, true peak and zero processing are explicit',()=>{const p=generatePrompt({...defaults,bass:-1.5,air:-.5,compression:1,width:0,saturation:0});assert.match(p,/Apply -1.5 dB bass EQ/);assert.match(p,/Apply -0.5 dB high-shelf/);assert.match(p,/Bypass added compression/);assert.match(p,/true-peak ceiling of -3 dBTP/);assert.doesNotMatch(p,/Analog saturation intent/);});
test('Export import preserves every preset and additional direction',()=>{for(const p of presets){const recipe={...p.recipe,notes:'Keep this phrase.',passage:'0:42 chorus'};const result=parseExport(JSON.stringify({schema:SCHEMA,version:2,name:p.name,recipe}));assert.deepEqual(result.recipe,normalizeRecipe(recipe));assert.equal(generatePrompt(result.recipe),generatePrompt(recipe));}assert.throws(()=>parseExport('{"version":3}'));assert.throws(()=>normalizeRecipe({version:99}));});
test('Gift off and stem off omit exports; overlay asks for supplied voice',()=>{const p=generatePrompt({...defaults,stems:'none',gift:'none'});assert.doesNotMatch(p,/Export vocals|gift edit/);assert.match(generatePrompt({...defaults,gift:'voice'}),/only from a supplied voice recording/);assert.match(generatePrompt(defaults),/identical start time, length and sample rate/);});
