import {controls,defaults,modes,presets,normalizeRecipe,generatePrompt,parseExport,SCHEMA} from './recipe.mjs';
const $=id=>document.getElementById(id), KEY='juice-cans.audio-recipes.v2';
let recipe={...defaults}, saved=[], dirty=false, storageHealthy=true;
const notify=text=>{$('status').textContent=text;};
try { const raw=JSON.parse(localStorage.getItem(KEY)||'[]'); if(!Array.isArray(raw)) throw Error(); saved=raw.map(x=>({id:String(x.id),name:String(x.name).slice(0,80),recipe:normalizeRecipe(x.recipe)})); }
catch { storageHealthy=false; notify('Saved recipes could not be read. Existing data has been left untouched. Export JSON to keep your work.'); }
function persist(next){try{if(!storageHealthy)throw Error();localStorage.setItem(KEY,JSON.stringify(next));saved=next;return true;}catch{notify('Browser storage unavailable. Export JSON to keep this recipe.');return false;}}
function refreshSaved(selected=''){$('saved').replaceChildren(new Option('Choose a saved recipe…',''),...saved.map(x=>new Option(x.name,x.id)));$('saved').value=selected;selection();}
function selection(){const yes=saved.some(x=>x.id===$('saved').value);for(const id of ['load','delete','update'])$(id).disabled=!yes;}
for(const p of presets){const b=document.createElement('button');b.className='preset';b.type='button';const strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=p.name;span.textContent=p.description;b.append(strong,span);b.onclick=()=>{if(!discard())return;recipe={...p.recipe};$('recipe-name').value=p.name;dirty=false;render();notify(`${p.name} loaded. Save it to keep your changes.`);};$('presets').append(b);}
for(const [id,[label,short]] of Object.entries(modes)){const b=document.createElement('button');b.type='button';b.className='mode';b.dataset.mode=id;b.innerHTML=`<strong>${label}</strong><span>${short}</span>`;b.onclick=()=>{recipe.mode=id;dirty=true;render();};$('modes').append(b);}
for(const c of controls){const div=document.createElement('div');div.className='control';div.innerHTML=`<div class="control-head"><label for="slider-${c.id}">${c.label}</label><div class="numeric"><input id="number-${c.id}" type="number" min="${c.min}" max="${c.max}" step="${c.step}" aria-label="${c.label} value" aria-describedby="hint-${c.id}"><span>${c.unit}</span></div></div><input id="slider-${c.id}" type="range" min="${c.min}" max="${c.max}" step="${c.step}" aria-describedby="hint-${c.id}"><p class="hint" id="hint-${c.id}">${c.hint}</p>`;$(c.group+'-controls').append(div);for(const kind of ['slider','number']){const el=$(kind+'-'+c.id);el.addEventListener(kind==='slider'?'input':'change',()=>{const value=Number(el.value);if(!el.value||!Number.isFinite(value)){render();return;}recipe=normalizeRecipe({...recipe,[c.id]:value});dirty=true;render();});}}
function render(){recipe=normalizeRecipe(recipe);for(const c of controls){$('slider-'+c.id).value=recipe[c.id];$('number-'+c.id).value=recipe[c.id];$('slider-'+c.id).setAttribute('aria-valuetext',`${recipe[c.id]} ${c.unit}`);}document.querySelectorAll('[data-field]').forEach(el=>{if(el.type==='checkbox')el.checked=recipe[el.dataset.field];else el.value=recipe[el.dataset.field];});document.querySelectorAll('[data-mode]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.mode===recipe.mode)));$('mode-note').textContent=modes[recipe.mode][2];$('groove-fields').disabled=recipe.mode==='polish';$('gift-fields').hidden=recipe.gift==='none';$('quality').disabled=recipe.stems==='none';$('postprompt-textarea').value=generatePrompt(recipe);}
$('recipe-form').onsubmit=e=>e.preventDefault();
document.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('input',()=>{recipe[el.dataset.field]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;dirty=true;if(el.tagName==='TEXTAREA'||el.id==='passage')$('postprompt-textarea').value=generatePrompt(recipe);else render();}));
$('recipe-name').oninput=()=>{dirty=true;};
function discard(){return !dirty||confirm('Replace your unsaved changes? Save a recipe first to keep them.');}
$('reset').onclick=()=>{if(!discard())return;recipe={...defaults};$('recipe-name').value='Gentle Pocket';dirty=false;render();notify('Reset to Gentle Pocket. Saved recipes are unchanged.');};
function name(){return $('recipe-name').value.trim().slice(0,80)||'Untitled recipe';}
$('save').onclick=()=>{const id=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;const next=[...saved,{id,name:name(),recipe:normalizeRecipe(recipe)}];if(persist(next)){dirty=false;refreshSaved(id);notify('Recipe saved in this browser.');}};
$('saved').onchange=selection;
$('load').onclick=()=>{const entry=saved.find(x=>x.id===$('saved').value);if(!entry||!discard())return;recipe={...entry.recipe};$('recipe-name').value=entry.name;dirty=false;render();notify('Saved recipe loaded.');};
$('update').onclick=()=>{const id=$('saved').value,entry=saved.find(x=>x.id===id);if(!entry||!confirm(`Replace saved recipe “${entry.name}” with current settings?`))return;if(persist(saved.map(x=>x.id===id?{id,name:name(),recipe:normalizeRecipe(recipe)}:x))){dirty=false;refreshSaved(id);notify('Saved recipe updated.');}};
$('delete').onclick=()=>{const entry=saved.find(x=>x.id===$('saved').value);if(!entry||!confirm(`Delete “${entry.name}” from this browser?`))return;if(persist(saved.filter(x=>x.id!==entry.id))){refreshSaved();notify('Saved recipe deleted. Current controls are unchanged.');}};
$('export').onclick=()=>{const data={schema:SCHEMA,version:2,name:name(),recipe:normalizeRecipe(recipe),prompt:generatePrompt(recipe)};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=(name().replace(/[^a-z0-9_-]+/gi,'-')||'juice-cans')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Recipe JSON exported. Keep it as a backup or engine handoff.');};
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>100000)throw Error('Recipe file is too large (maximum 100 KB).');const data=parseExport(await file.text());if(!discard())return;recipe=data.recipe;$('recipe-name').value=data.name;dirty=true;render();notify('Recipe imported. Save it to keep it in this browser.');}catch(err){notify(err.message||'Could not import recipe.');}finally{e.target.value='';}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(generatePrompt(recipe));notify('Prompt copied.');}catch{$('postprompt-textarea').focus();$('postprompt-textarea').select();notify('Select and copy the highlighted prompt using your browser’s Copy command.');}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
refreshSaved();render();
